name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Install devbox
        run: curl -fsSL https://get.jetify.com/devbox | bash -s -- -f

      - name: GoReleaser
        run: devbox run -- goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
